#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-epiR
Version  : 2.0.77
Release  : 85
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/epiR_2.0.77.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/epiR_2.0.77.tar.gz
Summary  : Tools for the Analysis of Epidemiological Data
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-BiasedUrn
Requires: R-flextable
Requires: R-lubridate
Requires: R-officer
Requires: R-pander
Requires: R-sf
Requires: R-zoo
BuildRequires : R-BiasedUrn
BuildRequires : R-flextable
BuildRequires : R-lubridate
BuildRequires : R-officer
BuildRequires : R-pander
BuildRequires : R-sf
BuildRequires : R-zoo
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -n epiR
pushd ..
cp -a epiR buildavx2
popd
pushd ..
cp -a epiR buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732034662

%install
export SOURCE_DATE_EPOCH=1732034662
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/epiR/DESCRIPTION
/usr/lib64/R/library/epiR/INDEX
/usr/lib64/R/library/epiR/Meta/Rd.rds
/usr/lib64/R/library/epiR/Meta/data.rds
/usr/lib64/R/library/epiR/Meta/features.rds
/usr/lib64/R/library/epiR/Meta/hsearch.rds
/usr/lib64/R/library/epiR/Meta/links.rds
/usr/lib64/R/library/epiR/Meta/nsInfo.rds
/usr/lib64/R/library/epiR/Meta/package.rds
/usr/lib64/R/library/epiR/Meta/vignette.rds
/usr/lib64/R/library/epiR/NAMESPACE
/usr/lib64/R/library/epiR/NEWS
/usr/lib64/R/library/epiR/R/epiR
/usr/lib64/R/library/epiR/R/epiR.rdb
/usr/lib64/R/library/epiR/R/epiR.rdx
/usr/lib64/R/library/epiR/data/epi.SClip.RData
/usr/lib64/R/library/epiR/data/epi.epidural.RData
/usr/lib64/R/library/epiR/data/epi.incin.RData
/usr/lib64/R/library/epiR/doc/epiR_descriptive.R
/usr/lib64/R/library/epiR/doc/epiR_descriptive.Rmd
/usr/lib64/R/library/epiR/doc/epiR_descriptive.html
/usr/lib64/R/library/epiR/doc/epiR_measures_of_association.R
/usr/lib64/R/library/epiR/doc/epiR_measures_of_association.Rmd
/usr/lib64/R/library/epiR/doc/epiR_measures_of_association.html
/usr/lib64/R/library/epiR/doc/epiR_sample_size.R
/usr/lib64/R/library/epiR/doc/epiR_sample_size.Rmd
/usr/lib64/R/library/epiR/doc/epiR_sample_size.html
/usr/lib64/R/library/epiR/doc/epiR_surveillance.R
/usr/lib64/R/library/epiR/doc/epiR_surveillance.Rmd
/usr/lib64/R/library/epiR/doc/epiR_surveillance.html
/usr/lib64/R/library/epiR/doc/index.html
/usr/lib64/R/library/epiR/help/AnIndex
/usr/lib64/R/library/epiR/help/aliases.rds
/usr/lib64/R/library/epiR/help/epiR.rdb
/usr/lib64/R/library/epiR/help/epiR.rdx
/usr/lib64/R/library/epiR/help/figures/logo.pdf
/usr/lib64/R/library/epiR/help/figures/logo.png
/usr/lib64/R/library/epiR/help/figures/logo.svg
/usr/lib64/R/library/epiR/help/figures/qrcode_apps.apple.com.png
/usr/lib64/R/library/epiR/help/figures/qrcode_play.google.com.png
/usr/lib64/R/library/epiR/help/paths.rds
/usr/lib64/R/library/epiR/html/00Index.html
/usr/lib64/R/library/epiR/html/R.css
